### PR TITLE
Added some small changes & regex

### PR DESCRIPTION
**Pull request by chs000-00**

### CODE REVIEW

**Comment by chs000-00** [comment]
Regex probably needs to be added for pywordle to work

**Review by NeonG4 — APPROVED** [review]
Does the same thing though?

**Comment by chs000-00** [comment]
what do you mean by that?

**Comment by NeonG4** [comment]
It didn't really change anything...

**Comment by chs000-00** [comment]
most likely will be useful in the future, also you should prob delete the entire "do you want to play wordle thing"

**Pull request merged**
